name: Publish Docker image

on:
  push:
    paths:
      - 'src/**'
      - 'morphir.json'
      - 'package.json'
      - 'elm.json'
      - '.github/workflows/publish-docker.yml'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@2.1.0
        with:
          username: finos
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@4.1.1
        with:
          images: finos/lcr-interactive
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3.2.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}